<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <AssemblyName>cella</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Cella.Core\Cella.Core.csproj" />
  </ItemGroup>

</Project>
