<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Cella.SourceGenerators\Cella.SourceGenerators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="CsToml" Version="1.8.2" />
    <PackageReference Include="CsToml.Generator" Version="1.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="libLLVM" Version="20.1.2" />
    <PackageReference Include="LLVMSharp" Version="20.1.2" />
  </ItemGroup>

</Project>
