<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Cella.SourceGenerators\Cella.SourceGenerators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="libLLVM" Version="21.1.8" />
    <PackageReference Include="LLVMSharp" Version="20.1.2" />
  </ItemGroup>

</Project>
